from django.contrib import admin
from models import *

admin.site.register(Usuario)
admin.site.register(Estado)
admin.site.register(Region)
admin.site.register(Ciudad)
admin.site.register(Comuna)
admin.site.register(SolicitudDeCompra)
admin.site.register(PuestoDeTrabajo)
admin.site.register(Material)
admin.site.register(DetalleSolicitudDeCompra)
admin.site.register(Composicion)
admin.site.register(Lote)
admin.site.register(Proveedor)
admin.site.register(OrdenDeCompra)
admin.site.register(DetalleOrdenDeCompra)
admin.site.register(EstadoOF)
admin.site.register(OrdenDeFabricacion)
admin.site.register(Etapa)
admin.site.register(OrdenDeTrabajo)
admin.site.register(Maquinaria)
admin.site.register(Notificacion)
admin.site.register(Consumo)
admin.site.register(Auditoria)
